# Generated by Django 3.2.8 on 2021-12-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pd_drug',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('npi', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('credential', models.CharField(max_length=10)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='Statedata',
            fields=[
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('drugname', models.ForeignKey(db_column='drugname', on_delete=django.db.models.deletion.DO_NOTHING, to='opioidSite.drug')),
                ('prescriberid', models.ForeignKey(db_column='prescriberid', on_delete=django.db.models.deletion.DO_NOTHING, to='opioidSite.prescriber')),
            ],
            options={
                'db_table': 'pd_triple',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='opioidSite.statedata'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='uir_triple',
            field=models.ManyToManyField(through='opioidSite.Triple', to='opioidSite.Drug'),
        ),
        migrations.AddField(
            model_name='drug',
            name='uir_triple',
            field=models.ManyToManyField(through='opioidSite.Triple', to='opioidSite.Prescriber'),
        ),
    ]
