# Generated by Django 3.2.8 on 2021-12-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opioidSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triple',
            name='drugname',
            field=models.ForeignKey(db_column='drugname', on_delete=django.db.models.deletion.CASCADE, to='opioidSite.drug'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='prescriberid',
            field=models.ForeignKey(db_column='prescriberid', on_delete=django.db.models.deletion.CASCADE, to='opioidSite.prescriber'),
        ),
    ]
