# Generated by Django 3.2.8 on 2021-12-07 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opioidSite', '0002_auto_20211206_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugname',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Name of prescription'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='isopioid',
            field=models.CharField(max_length=5, verbose_name='Is it an opioid (true/false)'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='isopioidprescriber',
            field=models.CharField(max_length=5, verbose_name='Do they prescribe opioids (true/false)'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='npi',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='National Provider Identifier'),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='totalprescriptions',
            field=models.IntegerField(default=0, verbose_name='Total amount of prescriptions'),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='Opioid Deaths'),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='stateabbrev',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='drugname',
            field=models.ForeignKey(db_column='drugname', on_delete=django.db.models.deletion.CASCADE, to='opioidSite.drug', verbose_name='Name of prescription'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='prescriberid',
            field=models.ForeignKey(db_column='prescriberid', on_delete=django.db.models.deletion.CASCADE, to='opioidSite.prescriber', verbose_name='Prescriber Name'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantity Prescribed'),
        ),
    ]
